// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package examplepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type User struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32              `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Address              *Address           `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	AddressMap           map[int32]*Address `protobuf:"bytes,5,rep,name=addressMap,proto3" json:"addressMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AddressList          []*Address         `protobuf:"bytes,6,rep,name=addressList,proto3" json:"addressList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *User) GetAddressMap() map[int32]*Address {
	if m != nil {
		return m.AddressMap
	}
	return nil
}

func (m *User) GetAddressList() []*Address {
	if m != nil {
		return m.AddressList
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "example.Address")
	proto.RegisterType((*User)(nil), "example.User")
	proto.RegisterMapType((map[int32]*Address)(nil), "example.User.AddressMapEntry")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0x03, 0x31,
	0x14, 0x24, 0xd9, 0x4d, 0x17, 0xdf, 0x6a, 0x2d, 0x0f, 0x0f, 0x41, 0x10, 0x96, 0x1e, 0x64, 0xf1,
	0xb0, 0xc2, 0xf6, 0x22, 0x8a, 0x07, 0x05, 0x6f, 0x16, 0x21, 0xe0, 0xc5, 0x5b, 0xea, 0x06, 0x59,
	0xec, 0x47, 0xd8, 0x44, 0xb1, 0xff, 0xc9, 0x1f, 0x29, 0xf9, 0x92, 0xa2, 0xbd, 0xcd, 0x24, 0x33,
	0xf3, 0xe6, 0x25, 0x70, 0xa4, 0xbe, 0xe4, 0x4a, 0x2f, 0x55, 0xa3, 0x87, 0x8d, 0xdd, 0x60, 0x11,
	0xe9, 0x74, 0x06, 0xc5, 0x5d, 0xd7, 0x0d, 0xca, 0x18, 0x44, 0xc8, 0x5f, 0x7b, 0xbb, 0xe5, 0xa4,
	0x22, 0xf5, 0x81, 0xf0, 0x18, 0x4f, 0x80, 0x19, 0x2b, 0xad, 0xe2, 0xd4, 0x1f, 0x06, 0x32, 0xfd,
	0xa6, 0x90, 0x3f, 0x1b, 0x35, 0xe0, 0x18, 0x68, 0xdf, 0x45, 0x03, 0xed, 0x3b, 0x17, 0xb1, 0x96,
	0xab, 0xa4, 0xf6, 0x18, 0x27, 0x90, 0xc9, 0x37, 0xc5, 0xb3, 0x8a, 0xd4, 0x4c, 0x38, 0x88, 0x17,
	0x50, 0xc8, 0x30, 0x93, 0xe7, 0x15, 0xa9, 0xcb, 0x76, 0xd2, 0xa4, 0x76, 0xb1, 0x8b, 0x48, 0x02,
	0xbc, 0x05, 0x88, 0x70, 0x2e, 0x35, 0x67, 0x55, 0x56, 0x97, 0xed, 0xd9, 0xaf, 0xdc, 0x95, 0x48,
	0x9e, 0xb9, 0xd4, 0x0f, 0x6b, 0x3b, 0x6c, 0xc5, 0x8e, 0x01, 0x5b, 0x28, 0x23, 0x7b, 0xec, 0x8d,
	0xe5, 0x23, 0xef, 0xff, 0x3f, 0x6e, 0x57, 0x74, 0xfa, 0x04, 0xc7, 0x7f, 0x22, 0xdd, 0x0e, 0xef,
	0x2a, 0xbc, 0x0c, 0x13, 0x0e, 0xe2, 0x39, 0xb0, 0x4f, 0xb9, 0xfc, 0x08, 0xab, 0xee, 0x8b, 0x0c,
	0xd7, 0xd7, 0xf4, 0x8a, 0xdc, 0x8f, 0x5f, 0x0e, 0x9b, 0xcb, 0x9b, 0x28, 0xd0, 0x8b, 0xc5, 0xc8,
	0xff, 0xc1, 0xec, 0x27, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x9d, 0x1c, 0xa0, 0x94, 0x01, 0x00, 0x00,
}
